### PR TITLE
clipctl: add start and stop clipmenud daemon options

### PR DESCRIPTION
**Pull request by mehw**
Hello,

This is to propose to add **start/stop clipmenud daemon** functionality to `clipctl`.

Let me know what you think.

Thanks.

### CODE REVIEW

**Comment by cdown** [comment]
Hmm, what's the use case? Ideally clipmenud should be managed by a service manager anyway, so unless there's some compelling reason I'd rather leave that to do it.

**Comment by mehw** [comment]
This is to have manual control. Not everyone uses a service manager like `systemd`...

For instance, this is an universal way to start/stop the service. The daemon `clipmenud` is efficient, starting and stopping it should be practical too, without any overhead, and `clipctl` already presents itself as a way to control the daemon.

**Comment by cdown** [comment]
If that's the only reason then I don't think it's particularly compelling, one might as well just run `pkill clipmenud` or start `clipmenud`. The only reason `-USR1` and `-USR2` have enable/disable is because the signal used is an implementation detail, but SIGTERM/SIGINT aren't.

**Comment by cdown** [comment]
Closing this out without prejudice based on the above comment.

**Comment by mehw** [comment]
> If that's the only reason then I don't think it's particularly compelling, one might as well just run `pkill clipmenud` or start `clipmenud`. The only reason `USR1` and `USR2` are mapped to disable/enable is because the signal used is an implementation detail, but SIGTERM/SIGINT aren't.

I agree. Thanks for the explanation.

**Pull request closed without merging**
