### PR TITLE
WIP: Use clipnotify loop mode if available

### LINKED ISSUE #195: Use clipnotify loop mode
Once clipmenu 2 is out, we should be able to use the new loop mode in https://github.com/cdown/clipnotify/commit/c04a22ed5322c3aecf10697a024731ad25a772a8.

### PR DESCRIPTION
**Pull request by N-R-K**
Closes: https://github.com/cdown/clipmenu/issues/195

### CODE REVIEW

**Comment by N-R-K** [comment]
Very rough draft, feedback welcome.

**Comment by cdown** [comment]
Hey! I'm actually in the (highly belated, given all the xclip/xsel pain) process of rewriting clipmenu{,d} in C and should have a working prototype some time this week. Maybe you'd be interested in giving feedback?

**Comment by cdown** [comment]
The C rewrite is at 70cc5d2b6a2027ba186f1555c0e114c53dc7c578 -- feel free to try it out.

**Comment by cdown** [comment]
Closing since this applies to the old bash version, but any feedback on clipmenu 7 of course very welcome :)

**Comment by N-R-K** [comment]
> The C rewrite is at [70cc5d2](https://github.com/cdown/clipmenu/commit/70cc5d2b6a2027ba186f1555c0e114c53dc7c578) -- feel free to try it out.

This looks interesting. I'll try to test it sometime this week and report back if I find anything. Cheers.

**Pull request closed without merging**
