### PR TITLE
Use xdotool instead of cat when CM_OUTPUT_CLIP

### PR DESCRIPTION
**Pull request by mil-ad**
This allows pasting directly in other non-terminal programs. For example a browser's address bar.

### CODE REVIEW

**Comment by cdown** [comment]
Hi there! Please maintain backwards compatibility of options :-)

It's also not acceptable to make xdotool mandatory, sorry. Please see how we already handle similar cases elsewhere.

**Comment by cdown** [comment]
Closing without prejudice due to lack of response to feedback.

**Comment by tblancher** [comment]
I wouldn't do this in clipmenu itself.  You should be able to assign this to however you launch clipmenu in your WM or DE.  For XMonad, I linked the following to my desired keybinding:

`spawn "clipmenu && xdotool key Ctrl+v"`

Replace "Ctrl+v" with whichever key binding you use for pasting.

**Comment by johnwuelk** [comment]
Thanks! `... && xdotool key Ctrl+v` works flawless! I use xdotool anyway for various scripts.

**Comment by nick87720z** [comment]
For case of interesting - text typing works with `xdotool type ...`, just needs '\r' replaced with '\r'. Though it may cause strange problem after use - when I did it against leafpad editor, it did not react to more key presses for short time, also Ctrl+Backspace did not work few times, when I used it to delete pasted text.

**Comment by nick87720z** [comment]
I'm experimenting with clipmenu, trying to extend its own rofi-script mode with some operations. Of course, not sure if they are necessary to be right in that file.

This is snippet from `case $ROFI_RETV` block (in this case assigned to 2nd custom command):
```
11) chosen_line="$1"
        sed -E 's|(["\$])|\\\1|g
                s|$|\r|
                1s/^/xdotool type --clearmodifiers --delay 20 -- "/
                $s/$/"/' \
        < "${cache_dir}/$(printf '%s\n' "$chosen_line" | cksum)" | sh >/dev/null &
        exit;
```
Sure, 3rd mouse button simulation would be also useful. Or even more reliable (if any text is placed to selection - mouse paste works in far more cases).

**Pull request closed without merging**
